### ISSUE TITLE
Issue with Version 5.0.0

### ISSUE THREAD

**Issue by SomeRandomOwl** [HookyQR/VSCodeBeautify#312]
So information on my current environment

OS | Version
----|---------
Windows10 | Build 17134

VSCode Version: 1.33.1

Extension | Version
-----------|----------
vscode-sqlite | 0.6.0
vscode-node-readme | 3.0.2
path-intellisense | 1.4.2
bracket-pair-colorizer-2 | 0.0.28
jshint | 0.10.20
vscode-eslint | 1.8.2
githistory| 0.4.6
gitlens | 9.7.3
vscode-html-css | 0.2.0
vscode-npm-script | 0.3.7
prettier-vscode | 1.9.0
gc-excelviewer | 2.1.32
beautify | 1.5.0
minify | 0.4.3
discord-vscode | 3.6.0
vscode-edit-csv | 0.0.11
docthis | 0.7.1
vscode-sshfs | 1.16.2
node-module-intellisense | 1.5.0
ftp-sync | 0.3.9
rainbow-csv | 1.0.0
cpptools | 0.23.0
csharp | 1.19.1
vsliveshare | 1.0.181
material-icon-theme | 3.7.0
polacode | 0.3.2
github-plus-theme | 1.2.0
better-align | 1.1.6
Material-theme | 2.23.0
html-css-class-completion | 1.18.0

Using Default Configs
Issue: Upon using Ctrl+Shift+P and doing the command Beautify file the following popup appears
`command 'HookyQR.beautifyFile' not found`
Same issue happens when I use Beautify Selection
`command 'HookyQR.beautify' not found`

Issue fixed by reverting the installed version of beautify to version 1.4.11

I don't know if this is a issue of one of my extensions conflicting with beautify or if it was with the update that happened 10 days ago.

It was working before the update with the same extensions installed and after it stopped working.

I've looked at all my configs and as far as I am aware I haven't touched any of the configs for beautify so it seems to be operating on default settings when this error occurs

If you need further info to try to resolve this I'll be happy to help

**Comment by HookyQR** [comment]
Hi @Seth177, it's likely one of the other extensions you have is blowing up during the load process, in an unexpected way. When this happens, the extension loader dies, and all extensions yet to be loaded don't get to boot up. It's a long list you've got there, you might get lucky and see something of note in the dev tools (Help->Toggle Developer Tools). If it is beautify thats causing the issue, let me know.

**Comment by SomeRandomOwl** [comment]
Got a error log from the console 

Just from a cursory look it only seems to be js-beautify failing to load, i am not seeing any other module failing to load.

` [Extension Host] debugger listening on port 40576
extensionService.ts:800 Activating extension 'HookyQR.beautify' failed: Cannot find module 'js-beautify'.
_logMessageInConsole @ extensionService.ts:800
_logOrShowMessage @ extensionService.ts:814
(anonymous) @ mainThreadExtensionService.ts:65
(anonymous) @ errors.ts:184
n @ errors.ts:184
$onExtensionActivationError @ mainThreadExtensionService.ts:63
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
console.ts:134 [Extension Host] Activating extension `HookyQR.beautify` failed:  Cannot find module 'js-beautify'
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
console.ts:134 [Extension Host] Here is the error stack:  Error: Cannot find module 'js-beautify' 
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Function.t._load (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
    at Function.t.getExtensionPathIndex.then.a._load (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
    at Function.t.getExtensionPathIndex.then.r._load (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at n (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
    at Object.<anonymous> (C:\Users\seth177\.vscode\extensions\hookyqr.beautify-1.5.0\extension.js:3:14)
    at Object.<anonymous> (C:\Users\seth177\.vscode\extensions\hookyqr.beautify-1.5.0\extension.js:244:3)
    at Module.t._initNodeRequire.r._compile (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.t._load (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
    at Function.t.getExtensionPathIndex.then.a._load (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
    at Function.t.getExtensionPathIndex.then.r._load (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Function.i [as __$__nodeRequire] (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:31:542)
    at c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:717:918
    at E._doActivateExtension (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:718:2)
    at E._activateExtension (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:716:772)
    at E.<anonymous> (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:714:224)
    at Generator.next (<anonymous>)
    at n (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:11:176)
    at new Promise (<anonymous>)
    at n (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:975)
    at Object.actualActivateExtension (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:713:946)
    at p._activateExtension (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:457:765)
    at define._activateExtensions.i.length.Promise.all.o.map.e (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:457:449)
    at Array.map (<anonymous>)
    at p._activateExtensions (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:457:437)
    at p.activateByEvent (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:455:375)
    at E._activateByEvent (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:715:434)
    at E._handleEagerExtensions (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:719:365)
    at define._startExtensionHost._readyToRunExtensions.wait.then (c:\Users\seth177\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:722:430)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by masonlouchart** [comment]
Same here. `js-beautify` fails to load.
